from flask import Flask
from flask_mysqldb import MySQL
from flask_session import Session

app = Flask(__name__)

app.config["MYSQL_USER"] = 'root'
app.config["MYSQL_PASSWORD"] = 'beer'
app.config["MYSQL_DB"] = 'giraffe'
app.config["MYSQL_HOST"] = 'localhost'
app.config["SESSION_TYPE"] = 'filesystem'
app.config["SECRET_KEY"] = 'key' # secret key for sessions (signed cookies). Flask uses it to protect the contents of the user session against tampering.
app.config["WTF_CSRF_SECRET_KEY"] = 'key' # token for csrf protection of forms.
# secret keys can be generated by secrets.token_hex()
db = MySQL(app)

from pythonlibrary import routes, routes_admin, routes_op, routes_user